-- require("config")
vim.keymap.set("n", ";", [[:]])

require("nvn.packer_plugin")
require("nvn.nvim")
require("nvn.mapping")
require("nvn.config")
require("nvn.abbreviations")
require("nvn.functions")
require("nvn.telescope")

vim.cmd('source ~/.config/nvim/vimscript/functions.vim')
vim.cmd('source ~/.config/nvim/vimscript/globalVars.vim')
vim.cmd('source ~/.config/nvim/vimscript/leader.vim')
vim.cmd('source ~/.config/nvim/vimscript/move.vim')
vim.cmd('source ~/.config/nvim/vimscript/nvimrc.vim')
vim.cmd('source ~/.config/nvim/vimscript/vimrc.vim')
vim.cmd('source ~/.config/nvim/vimscript/tag-generation.vim')
vim.cmd('source ~/.config/nvim/vimscript/tertiary-leader.vim')
vim.cmd('source ~/.config/nvim/vimscript/after-plugin.vim')
