-- require("config")
vim.keymap.set("n", ";", [[:]])

require("packer_plugin")
require("nvim")
require("mapping")
require("config")
require("abbreviations")
require("functions")

vim.cmd('source ~/.config/nvim/vimscript/functions.vim')
vim.cmd('source ~/.config/nvim/vimscript/globalVars.vim')
vim.cmd('source ~/.config/nvim/vimscript/leader.vim')
vim.cmd('source ~/.config/nvim/vimscript/move.vim')
vim.cmd('source ~/.config/nvim/vimscript/nvimrc.vim')
vim.cmd('source ~/.config/nvim/vimscript/search.vim')
vim.cmd('source ~/.config/nvim/vimscript/vimrc.vim')
vim.cmd('source ~/.config/nvim/vimscript/tag-generation.vim')
vim.cmd('source ~/.config/nvim/vimscript/tertiary-leader.vim')
vim.cmd('source ~/.config/nvim/vimscript/after-plugin.vim')
