local M = {}

M.abbrev_man_conf = require("nvn.plugin_setup.abbrev_conf").fn
M.aerial_conf = require("nvn.plugin_setup.aerial_conf").fn
M.autopairs_conf = require("nvn.plugin_setup.autopairs_conf").fn
M.autotag_conf = require("nvn.plugin_setup.autotag_conf").fn
M.clangfmt_conf = require("nvn.plugin_setup.clangfmt_conf").fn
M.colors_conf = require("nvn.plugin_setup.colors_conf").fn
M.comment_conf = require("nvn.plugin_setup.comment_conf").fn
M.diffenhance_conf = require("nvn.plugin_setup.diffenhance_conf").fn
M.diffview_conf = require("nvn.plugin_setup.diffview_conf").fn
M.dirdiff_conf = require("nvn.plugin_setup.dirdiff_conf").fn
M.goto_preview_conf = require("nvn.plugin_setup.goto_preview_conf").fn
M.guess_indent_conf = require("nvn.plugin_setup.guess_indent_conf").fn
M.indent_blankline_conf = require("nvn.plugin_setup.indent_blankline_conf").fn
M.lazy_git_conf = require("nvn.plugin_setup.lazy_git_conf").fn
M.lightbuld_conf = require("nvn.plugin_setup.lightbuld_conf").fn
M.litee_conf = require("nvn.plugin_setup.litee_conf").fn
M.lua_fmt_conf = require("nvn.plugin_setup.lua_fmt_conf").fn
M.lualine_conf = require("nvn.plugin_setup.lualine_conf").fn
M.mason_conf = require("nvn.plugin_setup.mason_conf").fn
M.notify = require("nvn.plugin_setup.notify").fn
M.nvim_cmp_conf = require("nvn.plugin_setup.nvim_cmp_conf").fn
M.nvim_colorizer_conf = require("nvn.plugin_setup.nvim_colorizer_conf").fn
M.nvim_devicons_conf = require("nvn.plugin_setup.nvim_devicons_conf").fn
M.nvim_lspconfig_conf = require("nvn.plugin_setup.nvim_lspconfig_conf").fn
M.nvim_tree_conf = require("nvn.plugin_setup.nvim_tree_conf").fn
M.nvim_ufo_conf = require("nvn.plugin_setup.nvim_ufo_conf").fn
M.pep8_indent_conf = require("nvn.plugin_setup.pep8_indent_conf").fn
M.rose_pine_conf = require("nvn.plugin_setup.rose_pine_conf").fn
M.rust_conf = require("nvn.plugin_setup.rust_conf").fn
M.rustaceanvim = require("nvn.plugin_setup.rustaceanvim").fn
M.smart_split_conf = require("nvn.plugin_setup.smart_split_conf").fn
M.startify_conf = require("nvn.plugin_setup.startify_conf").fn
M.telescope_conf = require("nvn.plugin_setup.telescope_conf").fn
M.toggleterm_conf = require("nvn.plugin_setup.toggleterm_conf").fn
M.treesitter_conf = require("nvn.plugin_setup.treesitter_conf").fn
M.undotree_conf = require("nvn.plugin_setup.undotree_conf").fn
M.which_key_conf = require("nvn.plugin_setup.which_key_conf").fn
M.whitespace_conf = require("nvn.plugin_setup.whitespace_conf").fn

return M
