local M = {}

M.abbrev_man = require("nvn.plugin_setup.abbrev").fn
M.aerial = require("nvn.plugin_setup.aerial").fn
M.autopairs = require("nvn.plugin_setup.autopairs").fn
M.autotag = require("nvn.plugin_setup.autotag").fn
M.clangfmt = require("nvn.plugin_setup.clangfmt").fn
M.colors = require("nvn.plugin_setup.colors").fn
M.comment = require("nvn.plugin_setup.comment").fn
M.diffenhance = require("nvn.plugin_setup.diffenhance").fn
M.diffview = require("nvn.plugin_setup.diffview").fn
M.dirdiff = require("nvn.plugin_setup.dirdiff").fn
M.goto_preview = require("nvn.plugin_setup.goto_preview").fn
M.guess_indent = require("nvn.plugin_setup.guess_indent").fn
M.indent_blankline = require("nvn.plugin_setup.indent_blankline").fn
M.lazy_git = require("nvn.plugin_setup.lazy_git").fn
M.lightbuld = require("nvn.plugin_setup.lightbuld").fn
M.litee = require("nvn.plugin_setup.litee").fn
M.lua_fmt = require("nvn.plugin_setup.lua_fmt").fn
M.lualine = require("nvn.plugin_setup.lualine").fn
M.mason = require("nvn.plugin_setup.mason").fn
M.nvim_colorizer = require("nvn.plugin_setup.nvim_colorizer").fn
M.nvim_devicons = require("nvn.plugin_setup.nvim_devicons").fn
M.nvim_lspconfig = require("nvn.plugin_setup.nvim_lspconfig").fn
M.nvim_tree = require("nvn.plugin_setup.nvim_tree").fn
M.nvim_ufo = require("nvn.plugin_setup.nvim_ufo").fn
M.pep8_indent = require("nvn.plugin_setup.pep8_indent").fn
M.rose_pine = require("nvn.plugin_setup.rose_pine").fn
M.rust = require("nvn.plugin_setup.rust").fn
M.smart_split = require("nvn.plugin_setup.smart_split").fn
M.startify = require("nvn.plugin_setup.startify").fn
M.telescope = require("nvn.plugin_setup.telescope").fn
M.toggleterm = require("nvn.plugin_setup.toggleterm").fn
M.treesitter = require("nvn.plugin_setup.treesitter").fn
M.undotree = require("nvn.plugin_setup.undotree").fn
M.which_key = require("nvn.plugin_setup.which_key").fn
M.whitespace = require("nvn.plugin_setup.whitespace").fn

return M
