local use = require('utils').use

return {
  'folke/lazy.nvim', -- Package manager

  use 'abbrev_man_conf',
  use 'action_preview_conf', -- Code action preview
  use 'aerial_conf',
  use 'alpha_conf',
  use 'asyncrun_conf',
  use 'block_conf',
  use 'colorizer_conf',
  use 'comment_conf',
  use 'diagflow_conf',
  use 'diffview_conf',
  use 'dirdiff_conf',
  use 'easy_align_conf',
  use 'editor_config_conf',
  use 'feline_conf',
  use 'fidget_conf',
  use 'fzf_conf',
  use 'git_sign_conf',
  use 'goto_preview_conf',
  use 'guess_indent_conf',
  use 'hlsearch_conf',
  use 'incline_conf',
  use 'indent_blankline_conf',
  use 'inlay_hints_conf',
  use 'lazy_dev_conf',
  use 'lazy_git_conf',
  use 'lemonade_luasnip_conf',
  use 'litee_calltree_conf',
  use 'litee_conf',
  use 'lsp_signature_conf',
  use 'lspkind_conf',
  use 'luafmt_conf',
  use 'lualine_conf',
  use 'mason_conf',
  use 'messages_conf',
  use 'mini_ai_conf', -- Mini AI
  use 'mkdir_conf',
  use 'none_ls_conf',
  use 'notify_conf',
  use 'nvim_autopairs_conf',
  use 'nvim_blame_conf',
  use 'nvim_cmp_conf',
  use 'nvim_cmp_lsp_rs', -- CMP LSP for RS
  use 'nvim_colorizer_conf',
  use 'nvim_devicons_conf',
  use 'nvim_lightbulb_conf',
  use 'nvim_lspconfig_conf',
  use 'nvim_tree_conf',
  use 'nvim_ts_autotag_conf',
  use 'nvim_ufo_conf',
  use 'oceanic_next_conf',
  use 'onedark_conf',
  use 'pep8_indent_conf',
  use 'rainbow_delimiter_conf',
  use 'rose_pine_conf',
  use 'rust_conf',
  use 'rustaceanvim_conf',
  use 'smart_split_conf',
  use 'startify_conf',
  use 'telescope_conf',
  use 'toggle_term_conf',
  use 'toggle_view_conf', -- Menu to toggle various options
  use 'treesitter_conf',
  use 'tsc_conf',
  use 'typst_conf',             -- Typst configuration
  use 'ultimate_autopair_conf', -- Ultimate auto pair
  use 'undotree_conf',
  use 'vim_clang_format_conf',
  use 'vim_clippy_conf',
  use 'vim_colors_solarized_conf',
  use 'vim_diff_enhance_conf',
  use 'vim_eunuch_conf',
  use 'vim_fugitive_conf',
  use 'vim_github_link_conf',
  use 'vim_highlightedyank_conf',
  use 'vim_signify_conf',
  use 'vim_star_search_conf',
  -- Which key configured in toggle view
  use 'whichkey_conf',
  use 'whitespace_conf',
  use 'windows_conf',
}
